services:
  subconv-sing-box:
    image: wouisb/subconv-sing-box:latest
    container_name: subconv-sing-box
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./config.json:/app/config.json
